name: user_registration
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^3.3.4
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  cloud_firestore: ^5.4.5
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets :
    - assets/
